# Generated by Django 4.2.3 on 2023-09-12 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(10, 'Open'), (20, 'Closed')], default=10, verbose_name='status')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_carts', to='shop.region', verbose_name='cart region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='carts.cart', verbose_name='cart')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shelf', verbose_name='shelf')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart items',
            },
        ),
    ]
