# Generated by Django 4.2.3 on 2023-09-12 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProductLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='product limit size')),
            ],
            options={
                'verbose_name': 'Global product limit',
                'verbose_name_plural': 'Global product limits',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('limit_size', models.IntegerField(verbose_name='product limit size')),
                ('closed_access', models.BooleanField(default=False, verbose_name='closed access')),
                ('unlimited_access', models.BooleanField(default=False, verbose_name='unlimited access')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Shelf',
                'verbose_name_plural': 'Shelves',
            },
        ),
    ]
